# Generated by Django 2.0 on 2018-06-20 21:48

import businessplan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessplan',
            name='financials',
        ),
        migrations.AlterField(
            model_name='businessplan',
            name='plan',
            field=models.FileField(blank=True, null=True, upload_to=businessplan.models.get_upload_path_bp),
        ),
    ]
