# Generated by Django 2.0 on 2018-07-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180718_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeprofile',
            name='currency',
            field=models.CharField(choices=[('XUA', 'ADB Unit of Account (XUA)'), ('DZD', 'Algerian Dinar (DZD)'), ('THB', 'Baht (THB)'), ('XBA', 'Bond Markets Units European Composite Unit (EURCO) (XBA)'), ('BIF', 'Burundi Franc (BIF)'), ('XOF', 'CFA Franc BCEAO (XOF)'), ('XAF', 'CFA franc BEAC (XAF)'), ('CVE', 'Cape Verde Escudo (CVE)'), ('CLP', 'Chilean peso (CLP)'), ('KMF', 'Comoro Franc (KMF)'), ('CDF', 'Congolese franc (CDF)'), ('NIO', 'Cordoba Oro (NIO)'), ('GMD', 'Dalasi (GMD)'), ('XYZ', 'Default currency. (XYZ)'), ('DJF', 'Djibouti Franc (DJF)'), ('STD', 'Dobra (STD)'), ('EGP', 'Egyptian Pound (EGP)'), ('ETB', 'Ethiopian Birr (ETB)'), ('EUR', 'Euro (EUR)'), ('GHS', 'Ghana Cedi (GHS)'), ('XAU', 'Gold (XAU)'), ('GNF', 'Guinea Franc (GNF)'), ('GYD', 'Guyana Dollar (GYD)'), ('KES', 'Kenyan Shilling (KES)'), ('AOA', 'Kwanza (AOA)'), ('SLL', 'Leone (SLL)'), ('LRD', 'Liberian Dollar (LRD)'), ('LYD', 'Libyan Dinar (LYD)'), ('SZL', 'Lilangeni (SZL)'), ('MGA', 'Malagasy Ariary (MGA)'), ('MUR', 'Mauritius Rupee (MUR)'), ('MZN', 'Metical (MZN)'), ('MAD', 'Moroccan Dirham (MAD)'), ('NGN', 'Naira (NGN)'), ('ERN', 'Nakfa (ERN)'), ('NAD', 'Namibian Dollar (NAD)'), ('ANG', 'Netherlands Antillian Guilder (ANG)'), ('MRO', 'Ouguiya (MRO)'), ('TOP', 'Paanga (TOP)'), ('XPT', 'Platinum (XPT)'), ('GBP', 'Pound Sterling (GBP)'), ('BWP', 'Pula (BWP)'), ('ZAR', 'Rand (ZAR)'), ('KHR', 'Riel (KHR)'), ('RWF', 'Rwanda Franc (RWF)'), ('XDR', 'SDR (XDR)'), ('SCR', 'Seychelles Rupee (SCR)'), ('XAG', 'Silver (XAG)'), ('SOS', 'Somali Shilling (SOS)'), ('SSP', 'South Sudanese Pound (SSP)'), ('TZS', 'Tanzanian Shilling (TZS)'), ('TTD', 'Trinidad and Tobago Dollar (TTD)'), ('TND', 'Tunisian Dinar (TND)'), ('USN', 'US Dollar (Next day) (USN)'), ('USD', 'US Dollar (USD)'), ('UGX', 'Uganda Shilling (UGX)'), ('CLF', 'Unidad de Fomento (CLF)'), ('ZMK', 'Zambian Kwacha (ZMK)'), ('ZMW', 'Zambian Kwacha (ZMW)'), ('ZWD', 'Zimbabwe Dollar A/06 (ZWD)'), ('ZWN', 'Zimbabwe dollar A/08 (ZWN)'), ('ZWL', 'Zimbabwe dollar A/09 (ZWL)')], max_length=50),
        ),
    ]
