# Generated by Django 2.0 on 2018-06-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nicname',
            field=models.CharField(blank=True, max_length=165, null=True),
        ),
    ]
