# Generated by Django 2.0 on 2018-06-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_auto_20180616_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceltemplate',
            name='period_verbose',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
