# Generated by Django 2.0 on 2018-06-18 22:56

from django.db import migrations, models
import kpi.models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_exceltemplate_period_verbose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceltemplate',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to=kpi.models.get_upload_path),
        ),
    ]
